### ISSUE TITLE
分类

### ISSUE THREAD

**Issue by dingqy** [robotfor1999/awesome-xjtlu#1]
可以考虑给每个专业院系分给类？

**Comment by robotfor1999** [comment]
等信息量上去了会分的。现在因为比较少所以暂时不打算分啦。

**Comment by dingqy** [comment]
我是可以找一些今年大四的EE/CSEE的（包括我）写一些申请 利物浦 2+2之类的东西emm但我感觉现在这个样子有点乱，人稍微一多这玩意就没法维护了。最好还是先把整个东西的结构分清楚吧，这样人想加一些内容或者是维护起来也会方便很多

**Comment by dingqy** [comment]
但其实这玩意主要还是推广的问题，我之前想过在github上弄一个这样的东西，但是如果没有人维护和推广的话很难做起来，再加上github的先天要求稍微高一些。

**Comment by robotfor1999** [comment]
嗯好的。因为我是数学的不太懂你们那边的专业分类，我到时候把数学系这边的分好你们再参考一下可以吗。

**Comment by robotfor1999** [comment]
是的推广是的大问题。目前啥渠道都收吧只能。不过就是在理工科里面能推广使用都已经很不错了。让朋友写也是一种推广！感谢！

**Comment by robotfor1999** [comment]
维护目前我的时间还蛮空闲的，也有整理癖hh，不过最后应该还是得靠脚本吧，感谢建议。

**Comment by dingqy** [comment]
做个总的框架出来就行，ee cst这块我可以来做，但我也马上毕业了，暑假里还会管一管，之后就跑路了，没人维护的话可能里面的资料会很乱而且过时emm

主要还是推广，如果不能保证一定人数的学生知道这个，其实就没啥意义了。

肯定是需要一个脚本来自动化提交的，不然浪费时间有点多

**Comment by robotfor1999** [comment]
嗯嗯理解，谢谢了

**Comment by dingqy** [comment]
其实最好能得到学校的支持，比如说学校群邮，学校公众号之类的。

**Comment by robotfor1999** [comment]
嗯嗯是的，不过感觉还是得做出一定的成果先。

**Comment by robotfor1999** [comment]
hello文件框架已经重新搭建，readme还没来得及写，你和你的朋友们可以找到文件位置写一写了。谢谢分享！有啥修改的意见欢迎提出。

**Comment by robotfor1999** [comment]
hello文件框架已经重新搭建，readme还没来得及写，你和你的朋友们可以找到文件位置写一写了。谢谢分享！有啥修改的意见欢迎提出。 @dingqy

**Comment by robotfor1999** [comment]
把项目部署在github page上了，[链接](https://robotfor1999.github.io/awesome-xjtlu/#/)。要是编辑的话找找模板和位置，麻烦了！

**Comment by dingqy** [comment]
好的
