### ISSUE TITLE
经验分享手册链接失效

### ISSUE THREAD

**Issue by BestOwl** [robotfor1999/awesome-xjtlu#19]
![image](https://user-images.githubusercontent.com/8947026/115380789-85e75a80-a205-11eb-9a49-f2094df18123.png)
首页Readme上的经验分享手册链接失效，打开后404
正确的链接应该是：https://github.com/robotfor1999/awesome-xjtlu/blob/main/docs/经验分享手册.md

**Comment by robotfor1999** [comment]
已更改，感谢！
