### ISSUE TITLE
可以把对应项目的模板release发布，这样会更好找一些

### ISSUE THREAD

**Issue by dingqy** [robotfor1999/awesome-xjtlu#5]
如题

**Comment by robotfor1999** [comment]
好的收到。

**Comment by chongfengling** [comment]
## 结构与模板
- 申请总结的结构：docs/grad-application/school-of-science/applied-mathematics/    （此目录中添加markdown文件）
- 申请总结的模板：docs/grad-application/school-of-science/applied-mathematics/17-name-UK.md & readme.md
- 专业介绍的结构：intro-program/   （此目录中添加markdown文件）
- 专业介绍的模板：intro-program/est-16-weiyili.md & readme.md
- 课程介绍的结构：intro-module/year3/   （此目录中添加markdown文件）
- 课程介绍的模板：intro-module/mth2xx.md & readme.md
- 学习生活的结构：suzhou-liverpool/   （此目录中添加markdown文件）
- 学习生活的模板：suzhou-liverpool/liverpool0001.md & readme.md
## 接下来的工作
- 位于[Projects](https://github.com/robotfor1999/awesome-xjtlu/projects)中。
